import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ChangeEvent, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
// import answer from '../image/answer/sample_01.jpeg'

const Home: NextPage = () => {
  const [data, setData] = useState<string>();
  const [previewImage, setPreviewImage] = useState<string>();

  useEffect(
    () => {
      axios
        .get('http://127.0.0.1:5000/')
        .then((res) => {
          setData(res.data.message);
        })
        .catch((error) => console.error(error));
    }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>start</div>
      <div>{data}</div>
      <div>end</div>
      {/* <Image src={answer} alt='answer' /> */}
      <input
        id='image'
        name='image'
        type='file'
        onChange={(event: ChangeEvent<HTMLInputElement>) => {
          if (event?.target?.files?.[0]) {
            const file = event.target.files[0];
            const reader = new FileReader();
            reader.onloadend = () => {
              setPreviewImage(reader.result as string)
            };
            reader.readAsDataURL(file);
          }
        }} />
    </div>
  )
}

export default Home
